# Tables presented in the Publication

*Probabilistic Framework for Integration of Mass Spectrum and Retention Time Information in Metabolite Identification*

by: Eric Bach, Simon Rogers, John Williamson and Juho Rousu, 2020

In [22]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [23]:
result_version = "LATEST"

## Main Document

### Table Comparing the different MS+RT Score Intergration Methods

We compare performance of the different MS+RT score integration frameworks in **Table 2**.

In [32]:
from msmsrt_scorer.experiments.figures_and_tables import table__alternative_methods_comparison

res_global_score, res_global_sigf = table__alternative_methods_comparison(result_version)
res_global_score

# print(table__alternative_methods_comparison("..", test="wilcoxon_oneside", to_latex=True))

                                                     Top-1       Top-5  \
Dataset       Ionization Method
EA (Massbank) positive   MS + RT (Chain-graph)  23.9 (***)        59.2
                         MS + RT (MetFrag 2.2)  24.0 (***)        59.0
                         MS + RT (our)          27.3 (***)  61.6 (***)
                         Only MS                      21.2        59.0
              negative   MS + RT (Chain-graph)  27.2 (***)  59.5 (***)
                         MS + RT (MetFrag 2.2)  30.2 (***)  59.2 (***)
                         MS + RT (our)          28.7 (***)  61.9 (***)
                         Only MS                      22.8        57.6
CASMI 2016    positive   MS + RT (Chain-graph)        11.9        36.5
                         MS + RT (MetFrag 2.2)  13.7 (***)        36.2
                         MS + RT (our)          14.0 (***)  40.7 (***)
                         Only MS                      11.8        37.3
              negative   MS + RT (Chain-graph)  13.2 (***)  49.4 (***)
                         MS + RT (MetFrag 2.2)  14.0 (***)        42.0
                         MS + RT (our)          15.2 (***)  47.2 (***)
                         Only MS                      11.1        44.2

                                                    Top-10      Top-20
Dataset       Ionization Method
EA (Massbank) positive   MS + RT (Chain-graph)        70.1  79.1 (***)
                         MS + RT (MetFrag 2.2)        69.5        77.1
                         MS + RT (our)          72.9 (***)  80.7 (***)
                         Only MS                      69.7        77.6
              negative   MS + RT (Chain-graph)  72.4 (***)  81.8 (***)
                         MS + RT (MetFrag 2.2)  73.6 (***)  84.4 (***)
                         MS + RT (our)          73.8 (***)  83.6 (***)
                         Only MS                      69.5        78.5
CASMI 2016    positive   MS + RT (Chain-graph)  50.2 (***)  60.7 (***)
                         MS + RT (MetFrag 2.2)        46.2        57.5
                         MS + RT (our)          52.2 (***)  62.8 (***)
                         Only MS                      47.0        58.3
              negative   MS + RT (Chain-graph)  61.0 (***)  69.4 (***)
                         MS + RT (MetFrag 2.2)        55.5  71.2 (***)
                         MS + RT (our)           57.0 (**)  70.1 (***)
                         Only MS                      55.3        68.0

#### Pairwise test for significant improvement

**Table 4**: Is there a significant improvement of the row method over the column method?

In [33]:
res_global_sigf[1]

# print(res_global_sigf[1])

Method-2,Method-1,MS + RT (Chain-graph),MS + RT (MetFrag 2.2),MS + RT (our),Only MS
0,MS + RT (Chain-graph),n.s,n.s,n.s,8.0e-26
1,MS + RT (MetFrag 2.2),4.3e-08,n.s,n.s,5.8e-38
2,MS + RT (our),8.7e-24,6.1e-08,n.s,5.4e-39
3,Only MS,n.s,n.s,n.s,n.s

In [34]:
res_global_sigf[20]

# print(res_global_sigf[20])

Method-2,Method-1,MS + RT (Chain-graph),MS + RT (MetFrag 2.2),MS + RT (our),Only MS
0,MS + RT (Chain-graph),n.s,8.1e-04,n.s,4.3e-23
1,MS + RT (MetFrag 2.2),n.s,n.s,n.s,4.3e-10
2,MS + RT (our),2.1e-13,1.5e-14,n.s,1.5e-34
3,Only MS,n.s,n.s,n.s,n.s

In [36]:
print(table__alternative_methods_comparison(result_version, to_latex=True)[1][20])

\begin{tabular}{lllcccc}
\toprule
              Method-1 & MS + RT (Chain-graph) & MS + RT (MetFrag 2.2) & MS + RT (our) &  Only MS \\
\midrule
 MS + RT (Chain-graph) &                   n.s &               8.1e-04 &           n.s &  4.3e-23 \\
 MS + RT (MetFrag 2.2) &                   n.s &                   n.s &           n.s &  4.3e-10 \\
         MS + RT (our) &               2.1e-13 &               1.5e-14 &           n.s &  1.5e-34 \\
               Only MS &                   n.s &                   n.s &           n.s &      n.s \\
\bottomrule
\end{tabular}

### Comparison of MetFrag's and IOKR's used as MS2-Scorer

In **Table 5** we compare the performance of the MS+RT score integration, when different MS2-Scorers, here MetFrag and IOKR, are used to process the MS2-spectra.

In [37]:
from msmsrt_scorer.experiments.figures_and_tables import table__MetFrag_vs_IOKR_comparison

table__MetFrag_vs_IOKR_comparison(result_version)

  \msms{}-Scorers   Method  Top-1  Top-5  Top-10  Top-20
0            IOKR  MS + RT   26.7   52.1    62.5    70.3
1            IOKR  Only MS   25.1   49.5    60.3    67.6
2         MetFrag  MS + RT   21.3   52.9    64.0    74.3
3         MetFrag  Only MS   16.7   49.5    60.4    70.6

In [38]:
print(table__MetFrag_vs_IOKR_comparison(result_version, to_latex=True))

\begin{tabular}{@{}llcccc@{}}
\toprule
\msms{}-Scorers &   Method &  Top-1 &  Top-5 &  Top-10 &  Top-20 \\
\midrule
           IOKR &  MS + RT &   26.7 &   52.1 &    62.5 &    70.3 \\
           IOKR &  Only MS &   25.1 &   49.5 &    60.3 &    67.6 \\
        MetFrag &  MS + RT &   21.3 &   52.9 &    64.0 &    74.3 \\
        MetFrag &  Only MS &   16.7 &   49.5 &    60.4 &    70.6 \\
\bottomrule
\end{tabular}

### Comparison of different Candidate Set Definitions

#### MetFrag

Table 6.

In [39]:
from msmsrt_scorer.experiments.figures_and_tables import table__candidate_set_comparison

table__candidate_set_comparison(result_version, ms2scorer="MetFrag")

                                  Top-1       Top-5      Top-10      Top-20
Candidate Set Method
All           MS + RT (our)  14.6 (***)  44.0 (***)  54.6 (***)  66.5 (***)
              Only MS              11.4        40.7        51.2        63.2
Correct MF    MS + RT (our)  17.7 (***)  48.4 (***)  59.8 (***)  71.0 (***)
              Only MS              13.1        46.0        56.9        68.7

In [41]:
print(table__candidate_set_comparison(result_version, ms2scorer="MetFrag", to_latex=True))

\begin{tabular}{lcccc}
\toprule
Candidate Set &         Method &       Top-1 &       Top-5 &      Top-10 &      Top-20 \\
\midrule
          All &  MS + RT (our) &  14.6 (***) &  44.0 (***) &  54.6 (***) &  66.5 (***) \\
          All &        Only MS &        11.4 &        40.7 &        51.2 &        63.2 \\
   Correct MF &  MS + RT (our) &  17.7 (***) &  48.4 (***) &  59.8 (***) &  71.0 (***) \\
   Correct MF &        Only MS &        13.1 &        46.0 &        56.9 &        68.7 \\
\bottomrule
\end{tabular}

#### IOKR

Not shown in the paper. Maybe we can put it into the supplementary material.

In [12]:
table__candidate_set_comparison(result_version, ms2scorer="IOKR")

                                  Top-1       Top-5      Top-10      Top-20
Candidate Set Method
All           MS + RT (our)  26.1 (***)  48.3 (***)  59.9 (***)  69.1 (***)
              Only MS              24.4        46.0        58.4        65.5
Correct MF    MS + RT (our)        30.2        52.3  66.2 (***)        74.7
              Only MS              30.6        53.9        65.3        74.8

## Supplementary Material

### Aggregated Metabolite Identification Performance of the different Edge-potential Functions

Table S1.

In [42]:
from msmsrt_scorer.experiments.figures_and_tables import table__edgepotential_function_comparison

res_scores, res_p = table__edgepotential_function_comparison(result_version)

# print(table__edgepotential_function_comparison("..", to_latex=True, test="wilcoxon_twoside"))

FileNotFoundError: [Errno 2] No such file or directory: 'LATEST/EA_Massbank/results__TFG__gridsearch/application/tree_method=random__n_trees=128__make_order_prob=stepfun__param_selection_measure=topk_auc__norm_scores=none__mtype=max/ion_mode=positive__participant=MetFrag_2.4.5__8afe4a14__max_n_cand=inf__sort_candidates_by_ms2_score=0/trainset=MEOH_AND_CASMI_JOINT__keep_test=0__est=ranksvm__mol_rep=substructure_count/topk_casmi__max_n_ms2=100__sample_id=000.pkl.gz'

In [5]:
res_scores

                         Method  Top-1  Top-5  Top-10  Top-20
0  MS + RT (our, hinge_sigmoid)   21.3   52.5    64.2    74.2
1        MS + RT (our, sigmoid)   21.2   52.6    63.9    73.9
2        MS + RT (our, stepfun)   20.3   52.2    63.8    74.2
3                       Only MS   16.7   49.5    60.4    70.6

In [6]:
res_p

                         Method  Top-1  Top-5 Top-10 Top-20
0  MS + RT (our, hinge_sigmoid)  (***)  (***)  (***)  (***)
1        MS + RT (our, sigmoid)  (***)  (***)  (***)  (***)
2        MS + RT (our, stepfun)  (***)  (***)  (***)  (***)

Table showing the significance of the improvement over the baseline (Only MS) determined using the two-sided Wilcoxon signed-rank test.